name: "say-something-action"
description: "Outputs some values"
inputs:
  text-to-say:
    description: "Text to say"
    required: true
    default: "Hello, World"
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: composite
  steps:
      - name: 'Say welcome'
        shell: bash
        run: echo "Hello, Oliver"

      - name: 'Say good bye'
        shell: bash
        run: echo "Good bye, Oliver

      - id: random-number-generator
        run: echo "::set-output name=random-id::$(echo $RANDOM)"
        shell: bash