name: hello-world-with-included-actions

on:
  workflow_dispatch:
    inputs:
      your_name:
        description: 'Your name'
        required: true
        default: 'John'

jobs:
  say-hello-job:
    name: 'say hello job'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: foo
        uses: ./.github/actions/hello-world-composite-action
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash