name: hello-world-with-included-actions

on:
  workflow_dispatch:
    inputs:
      your_name:
        description: 'Your name'
        required: true
        default: 'John'

jobs:
  say-hello-job:
    name: 'say hello job'
    runs-on: ubuntu-latest
    steps:
      - name: 'Say welcome'
        run: echo "Hello, " ${{ github.event.inputs.your_name }}

      - uses: actions/checkout@v2

      - name: say-somewithing-with-action
        uses: ./.github/actions/say-something
